version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - app
    volumes:
      - static:/app/static

  app:
    build:
      dockerfile: deploy/python/Dockerfile
      context: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    environment:
      DEBUG: 'True'
      REDIS_CONNECTION: redis://redis:6379
      PYTHONBUFFERED: 1
    volumes:
      - static:/app/static

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
  static: