version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - app
    volumes:
      - static:/app/static

  app:
    build:
      dockerfile: deploy/python/Dockerfile
      context: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    environment:
      DEBUG: 'True'
      REDIS_CONNECTION: redis://redis:6379
      PYTHONBUFFERED: 1
      CACHE_HOST: 'db'
      CACHE_USER: 'postgres'
      CACHE_PASSWORD: 'postgres'
      CACHE_NAME: 'collect_vk_data'
      CACHE_PORT: 5432
      DB_HOST: '109.68.212.119'
      DB_USER: 'honepaUser2'
      DB_PASSWORD: 'jkodfgUJ$&*hfgjdn3#7'
      DB_NAME: 'collect_interes_vk_api'


    volumes:
      - static:/app/static

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=collect_vk_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data




volumes:
  db:
  static: