version: '3'

services:
  app: &app
    build:
      dockerfile: deploy/python/Dockerfile
      context: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      DB_HOST: postgres
      DEBUG: 'True'
      REDIS_CONNECTION: redis://redis:6379
      PYTHONBUFFERED: 1
    volumes:
      - static:/app/static

  celery:
    <<: *app
    working_dir: /app/src
    command: celery -A target_data worker -l debug
    ports: [ ]
    volumes: [ ]



  celery-beat:
    <<: *app
    working_dir: /app/src
    depends_on:
      - celery
    command: celery -A target_data beat -l debug
    ports: [ ]
    volumes: [ ]

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

volumes:
  static: