# Generated by Django 3.1.7 on 2021-10-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10000)),
                ('expired', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Api Ключ',
                'verbose_name_plural': 'Api Ключи',
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Координата',
                'verbose_name_plural': 'Координаты',
                'db_table': 'coordinate',
                'unique_together': {('x', 'y')},
            },
        ),
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
                'db_table': 'interest_category',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(max_length=100000)),
                ('count_of_person', models.BigIntegerField(default=0)),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('coordinate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='main.coord')),
                ('interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='main.interestcategory')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'db_table': 'result',
            },
        ),
    ]
