# Generated by Django 3.1.7 on 2021-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coord',
            name='x',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='coord',
            name='y',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
