# Generated by Django 3.1.7 on 2021-10-10 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_apikey_acc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='acc_id',
            field=models.CharField(default='1607049679', max_length=255),
        ),
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_executions', models.DateTimeField(null=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.interestcategory')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coord')),
            ],
            options={
                'db_table': 'pairs',
                'unique_together': {('interest', 'point')},
            },
        ),
    ]
