# Generated by Django 3.1.7 on 2021-10-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211010_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
