# Generated by Django 3.1.7 on 2021-10-29 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_apikey_is_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairsWithSexAndAge',
            fields=[
                ('pairs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.pairs')),
                ('is_male', models.BooleanField(null=True)),
                ('age_begin', models.IntegerField(null=True)),
                ('age_end', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'pairs_with_info',
            },
            bases=('main.pairs',),
        ),
        migrations.AddField(
            model_name='result',
            name='age_begin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='age_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='is_male',
            field=models.BooleanField(null=True),
        ),
    ]
