# Generated by Django 3.1.7 on 2021-10-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_apikey_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='age_begin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='age_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='is_male',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='PairsWithSexAndAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_male', models.BooleanField(null=True)),
                ('age_begin', models.IntegerField(null=True)),
                ('age_end', models.IntegerField(null=True)),
                ('last_executions', models.DateTimeField(null=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.interestcategory')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coord')),
            ],
            options={
                'db_table': 'pairs_with_info',
                'unique_together': {('interest', 'point', 'age_begin', 'age_end', 'is_male')},
            },
        ),
    ]
